### PR TITLE
Feature/nrl kartverket

### PR DESCRIPTION
**Pull request by EmilieSkog**

### CODE REVIEW

**Review by EmilieSkog — COMMENTED** [review]
merge conflict of Telemark-120/README.md must be re-commited with resolved changes
README.md is not to be deleted

**Review by ThomasRanvikEriksen — CHANGES_REQUESTED** [review]
Shouldnt the names be f. ex. Telemark-120-MV1_CU and not Telemark-120-30-MV1_CU?

Forgot to remove -30-?

**Comment by EmilieSkog** [comment]
> Shouldnt the names be f. ex. Telemark-120-MV1_CU and not Telemark-120-30-MV1_CU?
> 
> Forgot to remove -30-?

-30- is to indicate CGMES v3.0 ref previous namestandard [FileNameStandard.adoc](https://github.com/3lbits/CIM4NoUtility/blob/develop/DIGIN10/docs/FileNameStandard.adoc#initial-model) 
In this pull request the initial model naming standard has been changed from DIGIN10-\<CGMES version>-\<MAS>\_\<profile> to Telemark-\<size of model>-\<CGMES version>-\<MAS>\_\<profile> but we could modify the change

**Review by ThomasRanvikEriksen — APPROVED** [review]

**Review by ThomasRanvikEriksen — CHANGES_REQUESTED** [review]
Remove -30-

**Review by ThomasRanvikEriksen — APPROVED** [review]

**Pull request merged**
